### ISSUE TITLE
Cannot find module random-js

### ISSUE THREAD

**Issue by ghost** [hola/challenge_jsdash#5]
The following error comes out when I try to run app
```
> game/jsdash.js 

module.js:487
    throw err;
    ^

Error: Cannot find module 'random-js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/.../challenge_jsdash/game/jsdash.js:5:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```
OS: Linux Fedora 25
Nodejs: v8.1.3

**Comment by boyangwang** [comment]
Hi, you need to run `npm install` to install dependencies. It will work afterwards

**Comment by ghost** [comment]
Ah, it should be run inside `game` folder, didn't find package.json in the root directory. Maybe it's better update readme
