### ISSUE TITLE
Error when running in normal mode (without --in-process)

### ISSUE THREAD

**Issue by Butch-1337** [hola/challenge_jsdash#7]
When i run: node jsdash.js --ai=ai.js --log=log.json

```
{
    "cave_source": "generated",
    "seed": 662023880,
    "geometry": {
        "w": 40,
        "h": 22
    },
    "butterflies": 3,
    "ingredients": {
        " ": 25,
        ":": 50,
        "+": 10,
        "O": 10,
        "*": 5
    },
    "cave": [
        "########################################",
        "# :::::+::+::O   :::::::: : +:::  :O:::#",
        "#OO::::+: ::O+ :::: *O::  :: :*:::+:*O:#",
        "#:::: O::: O*::O    : :::::O+:O:*:: :::#",
        "#*+:O+:::+: ::OO  :: +OO*:O :+OO+ :::: #",
        "#  O::O+: :OOO:::+:+: *:O:: :+:: O   : #",
        "#: O ::::::: ::::  / ::: ::    :+:    +#",
        "#: +: : OO: :*: *::  +O: *: O :O: ::::+#",
        "#O+  *:::O :: +:::: :O:O:   ::  :::::O+#",
        "#: :: O::  **:: :::::OO::O  : :  ::: * #",
        "# OO O+::O:: :+ +::+* O: : :::OOOO::   #",
        "#: :::  : :O*: :+:::+ ::::::::* O+:::O:#",
        "# :O+  + +:O+ ::::+ : :: +OO:::::   :::#",
        "# +/    :::: :* : :::O:::::O*O O:: ::: #",
        "#::  +::  ::+ *: O:O   +:  ::::: ::*:  #",
        "# O: ::: :*::O :OO:* : *:O + *:::*O : :#",
        "#:+OO+:+ ::+:+:  OO ::: :++ : :/ O: +**#",
        "#:: :::::*::  : O::  : +:  :: :  O O:::#",
        "#::: + O+:+:  : O: :::::::::+O ::::OOOO#",
        "#:: :::   + ::OOA  :::::O: *  :  :O *O #",
        "# O: ::O   :: :::::+ ::+O :O +*O:O:: ::#",
        "########################################"
    ],
    "controller": "script",
    "script": "ai.js",
    "limit_frames": 1200,
    "limit_time": 120,
    "interval": 100,
    "fps": 10,
    "commands": "",
    "outcome": "error",
    "error": [
        "evalmachine.<anonymous>:1",
        "JSON.stringify(__hola_xyzzy__([\"########################################\",\"# :::::+::+::O   :::::::: : +:::  :O:::#\",\"#OO::::+: ::O+ :::: *O::  :: :*:::+:*O:#\",\"#:::: O::: O*::O    : :::::O+:O:*:: :::#\",\"#*+:O+:::+: ::OO  :: +OO*:O :+OO+ :::: #\",\"#  O::O+: :OOO:::+:+: *:O:: :+:: O   : #\",\"#: O ::::::: ::::  / ::: ::    :+:    +#\",\"#: +: : OO: :*: *::  +O: *: O :O: ::::+#\",\"#O+  *:::O :: +:::: :O:O:   ::  :::::O+#\",\"#: :: O::  **:: :::::OO::O  : :  ::: * #\",\"# OO O+::O:: :+ +::+* O: : :::OOOO::   #\",\"#: :::  : :O*: :+:::+ ::::::::* O+:::O:#\",\"# :O+  + +:O+ ::::+ : :: +OO:::::   :::#\",\"# +/    :::: :* : :::O:::::O*O O:: ::: #\",\"#::  +::  ::+ *: O:O   +:  ::::: ::*:  #\",\"# O: ::: :*::O :OO:* : *:O + *:::*O : :#\",\"#:+OO+:+ ::+:+:  OO ::: :++ : :/ O: +**#\",\"#:: :::::*::  : O::  : +:  :: :  O O:::#\",\"#::: + O+:+:  : O: :::::::::+O ::::OOOO#\",\"#:: :::   + ::OOA  :::::O: *  :  :O *O #\",\"# O: ::O   :: :::::+ ::+O :O +*O:O:: ::#\",\"########################################\",\"  0120  000000    ",
        "",
        "ReferenceError: __hola_xyzzy__ is not defined",
        "    at evalmachine.<anonymous>:1:16",
        "    at ContextifyScript.Script.runInContext (vm.js:53:29)",
        "    at Object.runInContext (vm.js:108:6)",
        "    at screen (...\\game\\loader.js:37:34)",
        "    at process.on.screen (...\\game\\controller.js:123:25)",
        "    at emitTwo (events.js:130:20)",
        "    at process.emit (events.js:213:7)",
        "    at handleMessage (internal/child_process.js:753:14)",
        "    at Pipe.channel.onread (internal/child_process.js:472:11)"
    ]
}
```
When run with --in-process all is ok.

**Comment by feldgendler** [comment]
I need to see your AI script with which this can be reproduced.

**Comment by Butch-1337** [comment]
I already have solved the problem. It was caused by commented code in end of file. When i delete it the problem was fixed

**Comment by feldgendler** [comment]
This was a minor bug in the loader, which is now fixed. Thank you for reporting it!
